// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc7uqPArxrYhkkXi3QacL-3Hty4-z4ZCQ',
    appId: '1:835089855797:web:ab68cef6b0c8cfcaf7c87c',
    messagingSenderId: '835089855797',
    projectId: 'natal-iq',
    authDomain: 'natal-iq.firebaseapp.com',
    storageBucket: 'natal-iq.firebasestorage.app',
    measurementId: 'G-JVJ4QPZT31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ68JXoBIPPxYTsez8ZwovoWt6h6rPhcs',
    appId: '1:835089855797:android:752b728dc98e3bcef7c87c',
    messagingSenderId: '835089855797',
    projectId: 'natal-iq',
    storageBucket: 'natal-iq.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1wLTLuKV4NHHydGbcn3JmW0dluPTVMY',
    appId: '1:835089855797:ios:b977fc4f7369c186f7c87c',
    messagingSenderId: '835089855797',
    projectId: 'natal-iq',
    storageBucket: 'natal-iq.firebasestorage.app',
    iosBundleId: 'com.nataliq.app',
  );
}
